import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/home.module.scss'
import Link from 'next/link'
import { ChangeEvent, FormEvent, useContext, useState } from 'react'
import { logo } from '../../public/images/index'
import { Input } from '@/components/ui/Input';
import { Button } from '@/components/ui/Button';
import { AuthContext } from '@/contexts/AuthContext'
import { toast } from 'react-toastify'
import { RiAlarmWarningFill } from 'react-icons/ri';
import { canSSRGuest } from '@/utils/canSSRGuest'

export default function Home() {
  const { signIn } = useContext(AuthContext);
  const [email, setEmail] = useState<string>('');
  const [password, setPassword] = useState<string>('');
  const [loading, setLoading] = useState<boolean>(false);

  async function handleLogin(evt: FormEvent) {
    evt.preventDefault();

    if (email === '' || password === '') {
      toast.warn('Preencha os dados', {
        position: toast.POSITION.TOP_CENTER,
        theme: 'dark',
        icon: RiAlarmWarningFill,
      });
      return;
    }

    setLoading(true);

    const data = {
      email,
      password
    }

    await signIn(data);

    setLoading(false);
  }

  return (
    <>
      <Head>
        <title>Pizzaria XTech - Faça seu login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.containerCenter}>
        <Image src={logo} alt="Logo Tech Pizzaria" />

        <div className={styles.login}>
          <form onSubmit={handleLogin}>
            <Input
              placeholder="Digite seu email"
              type="text"
              value={email}
              onChange={(ev: ChangeEvent<HTMLInputElement>) => setEmail(ev.target.value)}
            />

            <Input
              placeholder="Digite sua senha"
              type="password"
              value={password}
              onChange={(ev: ChangeEvent<HTMLInputElement>) =>
                setPassword(ev.target.value)
              }
            />

            <Button type="submit" loading={false}>
              Acessar
            </Button>
          </form>
          <Link href="/signup" className={styles.text}>
            Não possuí uma conta? Cadastre-se
          </Link>
        </div>
      </main>
    </>
  );
}

export const getServerSideProps = canSSRGuest(async (ctx) => {
  return {
    props: {}
  }
});
