import Head from 'next/head';
import Image from 'next/image';
import styles from '@/styles/home.module.scss';
import Link from 'next/link';
import { logo } from '../../../public/images/index';
import { Input } from '@/components/ui/Input';
import { Button } from '@/components/ui/Button';

export default function SignUp() {
  return (
    <>
      <Head>
        <title>Faça seu cadastro agora!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.containerCenter}>
        <Image src={logo} alt="Logo Sujeito Pizzaria" />

        <div className={styles.login}>
          <h1>Criando sua conta</h1>
          <form>
            <Input placeholder="Digite seu nome" type="text" />

            <Input placeholder="Digite seu email" type="text" />

            <Input placeholder="Digite sua senha" type="password" />

            <Button type="submit" loading={false}>
              Cadastrar
            </Button>
          </form>
          <Link href="/" className={styles.text}>
            Já possuí uma conta? Faça login!
          </Link>
        </div>
      </main>
    </>
  );
}
